config/routes.rb
Rails.application.routes.draw do
  resources :certificates do
    collection do
      post :import
      get :verify
    end
  end
  resources :groups
  resources :certificate_templates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :group
  validates :name, presence: true
  validates :email, presence: true
  has_one_attached :qr_code

  extend FriendlyId
  friendly_id :random_hex, use: %i[finders slugged]

  def random_hex
    SecureRandom.hex
  end

  # after_create :generate_qr if group.display_qr?
  # after_create :send_email if group.email?
  after_create :generate_qr
  after_create :send_email

  private

  def generate_qr
    GenerateQrService.new(self).call
  end

  def send_email
    CertificateMailer.with(certificate: self).created
  end
end

app/models/certificate_template.rb
class CertificateTemplate < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :certificate_template
  has_many :certificates
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certificate_templates_controller.rb
class CertificateTemplatesController < ApplicationController
  def index
    @certificate_templates = CertificateTemplate.all
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    CsvImportService.new(file: params[:file], group_id: params[:group_id]).call

    redirect_to request.referer, notice: 'Import started...'
  end

  def show
    @certificate = Certificate.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Certificate #{@certificate.slug}", # filename
        template: "certificate_templates/templates/#{@certificate.group.certificate_template.id}",
        formats: [:html],
        disposition: :inline,
        layout: 'pdf'
      end
    end
  end

  def verify
    validation_number = params[:validation_number]
    return unless validation_number.present?
    certificate = Certificate.find_by(slug: validation_number)
    # TODO: check if certificate has expired
    if certificate.present?
      redirect_to certificate_path(certificate), notice: 'Certificate exists and is valid!'
    else
      redirect_to verify_certificates_path, alert: 'Invalid!'
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @certificates = @group.certificates
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :certificate_template_id, :display_qr, :display_verify_link, :display_cert_id, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificate_templates_helper.rb
module CertificateTemplatesHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/certificate_templates/_certificate_template.html.erb
<%= link_to new_group_path(certificate_template_id: certificate_template.id) do %>
  <div class="bg-slate-300">
    <%= certificate_template.attributes %>
  </div>
<% end %>

app/views/certificate_templates/index.html.erb
<% @certificate_templates.each do |certificate_template| %>
  <%= render partial: 'certificate_templates/certificate_template', locals: { certificate_template: } %>
  <br>
<% end %>

app/views/certificate_templates/templates/2.html.erb
<%= modifications = OpenStruct.new(@certificate.modifications) %>

<%= @certificate.name %>
<%= @certificate.email %>

<%= modifications.issued_by %>
<%= modifications.issued_at %>
<%= modifications.description %>
<%= modifications.name %>

app/views/certificate_templates/templates/3.html.erb
<% modifications = OpenStruct.new(@certificate.modifications) %>

<div>
<%= @certificate.group.certificate_template.name %>
</div>

<div>
  <%= @certificate.name %>
  <%= @certificate.email %>
</div>

<div>
  <%= image_tag(@certificate.qr_code) if @certificate.qr_code.attached? %>
</div>

app/views/certificates/_certificate.html.erb
<%= link_to certificate_path(certificate) do %>
<div>
  <%= certificate.slug %>
  <%= certificate.name %>
  <%= certificate.email %>
  <%= certificate.modifications %>
  <%= image_tag certificate.qr_code if certificate.qr_code.attached? && certificate.group.display_qr?%>
</div>
<% end %>

app/views/certificates/show.html.erb
<%= @certificate.attributes %>

<hr>

<%= link_to 'Open PDF', certificate_path(@certificate, format: :pdf), target: :_blank %>

<hr>

<%= link_to "https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME&name=#{@certificate.group.certificate_template.name}&organizationId=86368163&issueYear=#{@certificate.created_at.year}
  &issueMonth=#{@certificate.created_at.month}&expirationYear=#{@certificate.created_at.year + 10}&expirationMonth=#{@certificate.created_at.month}&certUrl=#{request.url}
  &certId=#{@certificate.slug}", target: '_blank' do %>
  <img src="https://download.linkedin.com/desktop/add2profile/buttons/en_US.png " alt="LinkedIn Add to Profile button">
<% end %>

app/views/certificates/verify.html.erb
<%= alert %>

<div>
  Please enter the validation code found at the bottom right of the certificate.
  Click submit to verify the certification.
  Verification information is displayed above this text.
  After viewing the verification information, you may continue to use this form to verify additional certificates as needed.
</div>

<%= form_with url: verify_certificates_path, method: :get, data: { turbo: 'false' } do |form| %>
  <%= form.text_field :validation_number, placeholder: 'validation number' %>
  <%= form.submit 'Validate' %>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :certificate_template_id %>
    <%= form.text_field :certificate_template_id, value: (params[:certificate_template_id] || group.certificate_template.id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :display_qr %>
    <%= form.check_box :display_qr, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :display_verify_link %>
    <%= form.check_box :display_verify_link, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :display_cert_id %>
    <%= form.check_box :display_cert_id, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.check_box :email, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= group.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Certificate template:</strong>
    <%= group.certificate_template_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Display qr:</strong>
    <%= group.display_qr %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Display verify link:</strong>
    <%= group.display_verify_link %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Display cert:</strong>
    <%= group.display_cert_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= group.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this group", group, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this group', edit_group_path(group), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Groups</h1>
    <%= link_to 'New group', new_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="groups" class="min-w-full">
    <%= render @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @group %>

    <%= link_to 'Edit this group', edit_group_path(@group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this group', group_path(@group), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

<%= form_with url: import_certificates_path(group_id: @group.id), method: :post do |form| %>
  <%= form.file_field :file, accept: ".csv" %>
  <%= form.submit 'Import' %>
<% end %>

<h3>
  Certificates:
  <%= @certificates.count %>
</h3>

<% @certificates.each do |certificate| %>
  <%= render partial: 'certificates/certificate', locals: { certificate: } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certificateowl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= link_to 'Certificate Templates', certificate_templates_path %>
      <%= link_to 'Groups', groups_path %>
      <%= link_to 'Verify', verify_certificates_path %>
      <hr>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CertificateOwl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>